name: automerge
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
permissions:
  contents: write
  pull-requests: write
jobs:
  call:
    uses: ervwalter/renovate-config/.github/workflows/automerge.yml@3f1efdb110e6208db4aa8160693c29f172936f0c # main
