name: automerge
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
permissions:
  contents: write
  pull-requests: write
jobs:
  call:
    uses: ervwalter/renovate-config/.github/workflows/automerge.yml@cbf0e2d851bdab07c2c2826443e5501cdd1a74db # main
